blank_issues_enabled: true
contact_links:
  - name: Dpowcoin Core Security Policy
    url: https://github.com/dpowcore-project/dpowcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Dpowcoin Core Developers
    url: https://dpowcore.org
    about: Dpowcoin Core homepage
